# AUTO-GENERATED — do not edit. Run 'uv run duty generate_sync' to regenerate.

from vclient._sync.client import SyncVClient
from vclient._sync.registry import (
    sync_books_service,
    sync_campaigns_service,
    sync_chapters_service,
    sync_character_autogen_service,
    sync_character_blueprint_service,
    sync_character_traits_service,
    sync_characters_service,
    sync_clear_default_client,
    sync_companies_service,
    sync_configure_default_client,
    sync_default_client,
    sync_developer_service,
    sync_dicerolls_service,
    sync_dictionary_service,
    sync_global_admin_service,
    sync_options_service,
    sync_system_service,
    sync_users_service,
)

__all__ = [
    "SyncVClient",
    "sync_books_service",
    "sync_campaigns_service",
    "sync_chapters_service",
    "sync_character_autogen_service",
    "sync_character_blueprint_service",
    "sync_character_traits_service",
    "sync_characters_service",
    "sync_clear_default_client",
    "sync_companies_service",
    "sync_configure_default_client",
    "sync_default_client",
    "sync_developer_service",
    "sync_dicerolls_service",
    "sync_dictionary_service",
    "sync_global_admin_service",
    "sync_options_service",
    "sync_system_service",
    "sync_users_service",
]
