"""API client for the vclient service."""

from vclient.client import VClient
from vclient.config import APIConfig
from vclient.exceptions import (
    APIError,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    NotFoundError,
    RateLimitError,
    RequestValidationError,
    ServerError,
    ValidationError,
)
from vclient.registry import (
    books_service,
    campaigns_service,
    character_blueprint_service,
    character_traits_service,
    characters_service,
    companies_service,
    configure_default_client,
    default_client,
    developer_service,
    dictionary_service,
    global_admin_service,
    system_service,
    users_service,
)
from vclient.services import (
    BooksService,
    CampaignsService,
    CharacterBlueprintService,
    CharactersService,
    CharacterTraitsService,
    CompaniesService,
    DeveloperService,
    DictionaryService,
    GlobalAdminService,
    SystemService,
    UsersService,
)

__all__ = (
    "APIConfig",
    "APIError",
    "AuthenticationError",
    "AuthorizationError",
    "BooksService",
    "CampaignsService",
    "CharacterBlueprintService",
    "CharacterTraitsService",
    "CharactersService",
    "CompaniesService",
    "ConflictError",
    "DeveloperService",
    "DictionaryService",
    "GlobalAdminService",
    "NotFoundError",
    "RateLimitError",
    "RequestValidationError",
    "ServerError",
    "SystemService",
    "UsersService",
    "VClient",
    "ValidationError",
    "books_service",
    "campaigns_service",
    "character_blueprint_service",
    "character_traits_service",
    "characters_service",
    "companies_service",
    "configure_default_client",
    "default_client",
    "developer_service",
    "dictionary_service",
    "global_admin_service",
    "system_service",
    "users_service",
)
