"""API client for the vclient service."""

from vclient.client import VClient
from vclient.config import APIConfig
from vclient.endpoints import Endpoints
from vclient.exceptions import (
    APIError,
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    NotFoundError,
    RateLimitError,
    RequestValidationError,
    ServerError,
    ValidationError,
)
from vclient.models import (
    Company,
    CompanyPermissions,
    CompanySettings,
    CreateCompanyRequest,
    CreateDeveloperRequest,
    Developer,
    DeveloperCompanyPermission,
    DeveloperWithApiKey,
    FreeTraitChangesPermission,
    GrantAccessRequest,
    GrantXPPermission,
    ManageCampaignPermission,
    MeDeveloper,
    MeDeveloperCompanyPermission,
    MeDeveloperWithApiKey,
    PaginatedResponse,
    PermissionLevel,
    ServiceStatus,
    SystemHealth,
    UpdateCompanyRequest,
    UpdateDeveloperRequest,
    UpdateMeDeveloperRequest,
)
from vclient.registry import (
    companies_service,
    configure_default_client,
    default_client,
    developer_service,
    global_admin_service,
    system_service,
)
from vclient.services import (
    CompaniesService,
    DeveloperService,
    GlobalAdminService,
    SystemService,
)

__all__ = [
    "APIConfig",
    "APIError",
    "AuthenticationError",
    "AuthorizationError",
    "CompaniesService",
    "Company",
    "CompanyPermissions",
    "CompanySettings",
    "ConflictError",
    "CreateCompanyRequest",
    "CreateDeveloperRequest",
    "Developer",
    "DeveloperCompanyPermission",
    "DeveloperService",
    "DeveloperWithApiKey",
    "Endpoints",
    "FreeTraitChangesPermission",
    "GlobalAdminService",
    "GrantAccessRequest",
    "GrantXPPermission",
    "ManageCampaignPermission",
    "MeDeveloper",
    "MeDeveloperCompanyPermission",
    "MeDeveloperWithApiKey",
    "NotFoundError",
    "PaginatedResponse",
    "PermissionLevel",
    "RateLimitError",
    "RequestValidationError",
    "ServerError",
    "ServiceStatus",
    "SystemHealth",
    "SystemService",
    "UpdateCompanyRequest",
    "UpdateDeveloperRequest",
    "UpdateMeDeveloperRequest",
    "VClient",
    "ValidationError",
    "companies_service",
    "configure_default_client",
    "default_client",
    "developer_service",
    "global_admin_service",
    "system_service",
]
