"""Data models for API responses."""

from .books import (
    BookCreate,
    BookUpdate,
    CampaignBook,
    _BookRenumber,
)

# Backwards compatibility aliases for books
CreateBookRequest = BookCreate
RenumberBookRequest = _BookRenumber
UpdateBookRequest = BookUpdate
from .campaigns import (
    Campaign,
    CampaignCreate,
    CampaignUpdate,
)

# Backwards compatibility aliases for campaigns
CreateCampaignRequest = CampaignCreate
UpdateCampaignRequest = CampaignUpdate
from .chapters import (
    CampaignChapter,
    ChapterCreate,
    ChapterUpdate,
    _ChapterRenumber,
)

# Backwards compatibility aliases for chapters
CreateChapterRequest = ChapterCreate
RenumberChapterRequest = _ChapterRenumber
UpdateChapterRequest = ChapterUpdate
from .character_autogen import (
    ChargenSessionFinalizeDTO,
    ChargenSessionResponse,
    CreateAutogenerateDTO,
)
from .character_blueprint import (
    CharacterConcept,
    HunterEdge,
    HunterEdgePerk,
    SheetSection,
    TraitCategory,
    VampireClan,
    WerewolfAuspice,
    WerewolfTribe,
)
from .character_trait import (
    AssignCharacterTraitRequest,
    CharacterTrait,
    CharacterTraitModifyRequest,
    CharacterTraitValueOptionsResponse,
    CreateCharacterTraitRequest,
)
from .characters import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    EdgeAndPerks,
    HunterAttributes,
    HunterAttributesCreate,
    HunterAttributesUpdate,
    InventoryItem,
    InventoryItemCreate,
    InventoryItemUpdate,
    MageAttributes,
    Perk,
    VampireAttributes,
    VampireAttributesCreate,
    VampireAttributesUpdate,
    WerewolfAttributes,
    WerewolfAttributesCreate,
    WerewolfAttributesUpdate,
)
from .characters import (
    HunterEdge as CharacterHunterEdge,
)

# Backwards compatibility aliases for characters
CharacterEdgeAndPerksDTO = EdgeAndPerks
CharacterInventoryItem = InventoryItem
CharacterPerkDTO = Perk
CreateCharacterInventoryItemRequest = InventoryItemCreate
CreateCharacterRequest = CharacterCreate
HunterAttributesEdgeModel = CharacterHunterEdge
UpdateCharacterInventoryItemRequest = InventoryItemUpdate
UpdateCharacterRequest = CharacterUpdate
from .companies import (
    Company,
    CompanyPermissions,
    CompanySettings,
    CreateCompanyRequest,
    GrantAccessRequest,
    NewCompanyResponse,
    UpdateCompanyRequest,
)
from .developers import (
    MeDeveloper,
    MeDeveloperCompanyPermission,
    MeDeveloperWithApiKey,
    UpdateMeDeveloperRequest,
)
from .diceroll import CreateDicreollQuickrollRequest, CreateDicreollRequest, Dicreoll
from .dictionary import (
    CreateDictionaryTermRequest,
    DictionaryTerm,
    UpdateDictionaryTermRequest,
)
from .global_admin import (
    CreateDeveloperRequest,
    Developer,
    DeveloperCompanyPermission,
    DeveloperWithApiKey,
    UpdateDeveloperRequest,
)
from .pagination import PaginatedResponse
from .shared import (
    CharacterSpecialty,
    CreateNoteRequest,
    NameDescriptionSubDocument,
    Note,
    RollStatistics,
    S3Asset,
    Trait,
    UpdateNoteRequest,
    WerewolfGift,
    WerewolfRite,
)
from .system import SystemHealth
from .users import (
    CampaignExperience,
    CreateQuickrollRequest,
    CreateUserRequest,
    DiscordProfile,
    ExperienceAddRemoveRequest,
    Quickroll,
    UpdateQuickrollRequest,
    UpdateUserRequest,
    User,
)

__all__ = [
    "AssignCharacterTraitRequest",
    "BookCreate",
    "BookUpdate",
    "Campaign",
    "CampaignBook",
    "CampaignChapter",
    "CampaignCreate",
    "CampaignExperience",
    "CampaignUpdate",
    "ChapterCreate",
    "ChapterUpdate",
    "Character",
    "CharacterConcept",
    "CharacterCreate",
    "CharacterEdgeAndPerksDTO",  # Backwards compat alias for EdgeAndPerks
    "CharacterInventoryItem",  # Backwards compat alias for InventoryItem
    "CharacterPerkDTO",  # Backwards compat alias for Perk
    "CharacterSpecialty",
    "CharacterTrait",
    "CharacterTraitModifyRequest",
    "CharacterTraitValueOptionsResponse",
    "CharacterUpdate",
    "ChargenSessionFinalizeDTO",
    "ChargenSessionResponse",
    "Company",
    "CompanyPermissions",
    "CompanySettings",
    "CreateAutogenerateDTO",
    "CreateBookRequest",
    "CreateCampaignRequest",
    "CreateChapterRequest",
    "CreateCharacterInventoryItemRequest",  # Backwards compat alias for InventoryItemCreate
    "CreateCharacterRequest",  # Backwards compat alias for CharacterCreate
    "CreateCharacterTraitRequest",
    "CreateCompanyRequest",
    "CreateDeveloperRequest",
    "CreateDicreollQuickrollRequest",
    "CreateDicreollRequest",
    "CreateDictionaryTermRequest",
    "CreateNoteRequest",
    "CreateQuickrollRequest",
    "CreateUserRequest",
    "Developer",
    "DeveloperCompanyPermission",
    "DeveloperWithApiKey",
    "Dicreoll",
    "DictionaryTerm",
    "DiscordProfile",
    "EdgeAndPerks",
    "ExperienceAddRemoveRequest",
    "GrantAccessRequest",
    "HunterAttributes",
    "HunterAttributesCreate",
    "HunterAttributesEdgeModel",  # Backwards compat alias for HunterEdge
    "HunterAttributesUpdate",
    "HunterEdge",
    "HunterEdgePerk",
    "InventoryItem",
    "InventoryItemCreate",
    "InventoryItemUpdate",
    "MageAttributes",
    "MeDeveloper",
    "MeDeveloperCompanyPermission",
    "MeDeveloperWithApiKey",
    "NameDescriptionSubDocument",
    "NewCompanyResponse",
    "Note",
    "PaginatedResponse",
    "Perk",
    "Quickroll",
    "RenumberBookRequest",
    "RenumberChapterRequest",
    "RollStatistics",
    "S3Asset",
    "SheetSection",
    "SystemHealth",
    "Trait",
    "TraitCategory",
    "UpdateBookRequest",
    "UpdateCampaignRequest",
    "UpdateChapterRequest",
    "UpdateCharacterInventoryItemRequest",  # Backwards compat alias for InventoryItemUpdate
    "UpdateCharacterRequest",  # Backwards compat alias for CharacterUpdate
    "UpdateCompanyRequest",
    "UpdateDeveloperRequest",
    "UpdateDictionaryTermRequest",
    "UpdateMeDeveloperRequest",
    "UpdateNoteRequest",
    "UpdateQuickrollRequest",
    "UpdateUserRequest",
    "User",
    "VampireAttributes",
    "VampireAttributesCreate",
    "VampireAttributesUpdate",
    "VampireClan",
    "WerewolfAttributes",
    "WerewolfAttributesCreate",
    "WerewolfAttributesUpdate",
    "WerewolfAuspice",
    "WerewolfGift",
    "WerewolfRite",
    "WerewolfTribe",
]
