"""Data models for API responses."""

from .campaigns import (
    Campaign,
    CreateCampaignRequest,
    UpdateCampaignRequest,
)
from .companies import (
    Company,
    CompanyPermissions,
    CompanySettings,
    CreateCompanyRequest,
    FreeTraitChangesPermission,
    GrantAccessRequest,
    GrantXPPermission,
    ManageCampaignPermission,
    PermissionLevel,
    UpdateCompanyRequest,
)
from .developers import (
    MeDeveloper,
    MeDeveloperCompanyPermission,
    MeDeveloperWithApiKey,
    UpdateMeDeveloperRequest,
)
from .global_admin import (
    CreateDeveloperRequest,
    Developer,
    DeveloperCompanyPermission,
    DeveloperWithApiKey,
    UpdateDeveloperRequest,
)
from .pagination import PaginatedResponse
from .shared import (
    CreateNoteRequest,
    Note,
    RollStatistics,
    S3Asset,
    S3AssetParentType,
    S3AssetType,
    UpdateNoteRequest,
)
from .system import ServiceStatus, SystemHealth
from .users import (
    CampaignExperience,
    CreateQuickrollRequest,
    CreateUserRequest,
    DiscordProfile,
    ExperienceAddRemoveRequest,
    Quickroll,
    UpdateQuickrollRequest,
    UpdateUserRequest,
    User,
    UserRole,
)

__all__ = [
    "Campaign",
    "CampaignExperience",
    "Company",
    "CompanyPermissions",
    "CompanySettings",
    "CreateCampaignRequest",
    "CreateCompanyRequest",
    "CreateDeveloperRequest",
    "CreateNoteRequest",
    "CreateQuickrollRequest",
    "CreateUserRequest",
    "Developer",
    "DeveloperCompanyPermission",
    "DeveloperWithApiKey",
    "DiscordProfile",
    "ExperienceAddRemoveRequest",
    "FreeTraitChangesPermission",
    "GrantAccessRequest",
    "GrantXPPermission",
    "ManageCampaignPermission",
    "MeDeveloper",
    "MeDeveloperCompanyPermission",
    "MeDeveloperWithApiKey",
    "Note",
    "PaginatedResponse",
    "PermissionLevel",
    "Quickroll",
    "RollStatistics",
    "S3Asset",
    "S3AssetParentType",
    "S3AssetType",
    "ServiceStatus",
    "SystemHealth",
    "UpdateCampaignRequest",
    "UpdateCompanyRequest",
    "UpdateDeveloperRequest",
    "UpdateMeDeveloperRequest",
    "UpdateNoteRequest",
    "UpdateQuickrollRequest",
    "UpdateUserRequest",
    "User",
    "UserRole",
]
