"""Data models for API responses."""

from .books import (
    BookCreate,
    BookUpdate,
    CampaignBook,
    _BookRenumber,
)

# Backwards compatibility aliases for books
CreateBookRequest = BookCreate
RenumberBookRequest = _BookRenumber
UpdateBookRequest = BookUpdate
from .campaigns import (
    Campaign,
    CampaignCreate,
    CampaignUpdate,
)

# Backwards compatibility aliases for campaigns
CreateCampaignRequest = CampaignCreate
UpdateCampaignRequest = CampaignUpdate
from .chapters import (
    CampaignChapter,
    ChapterCreate,
    ChapterUpdate,
    _ChapterRenumber,
)

# Backwards compatibility aliases for chapters
CreateChapterRequest = ChapterCreate
RenumberChapterRequest = _ChapterRenumber
UpdateChapterRequest = ChapterUpdate
from .character_autogen import (
    ChargenSessionFinalizeDTO,
    ChargenSessionResponse,
    CreateAutogenerateDTO,
)
from .character_blueprint import (
    CharacterConcept,
    HunterEdge,
    HunterEdgePerk,
    SheetSection,
    TraitCategory,
    VampireClan,
    WerewolfAuspice,
    WerewolfTribe,
)
from .character_trait import (
    CharacterTrait,
    CharacterTraitValueOptionsResponse,
    TraitCreate,
    _TraitAssign,
    _TraitModify,
)

# Backwards compatibility aliases for character traits
AssignCharacterTraitRequest = _TraitAssign
CharacterTraitModifyRequest = _TraitModify
CreateCharacterTraitRequest = TraitCreate
from .characters import (
    Character,
    CharacterCreate,
    CharacterUpdate,
    EdgeAndPerks,
    HunterAttributes,
    HunterAttributesCreate,
    HunterAttributesUpdate,
    InventoryItem,
    InventoryItemCreate,
    InventoryItemUpdate,
    MageAttributes,
    Perk,
    VampireAttributes,
    VampireAttributesCreate,
    VampireAttributesUpdate,
    WerewolfAttributes,
    WerewolfAttributesCreate,
    WerewolfAttributesUpdate,
)
from .characters import (
    HunterEdge as CharacterHunterEdge,
)

# Backwards compatibility aliases for characters
CharacterEdgeAndPerksDTO = EdgeAndPerks
CharacterInventoryItem = InventoryItem
CharacterPerkDTO = Perk
CreateCharacterInventoryItemRequest = InventoryItemCreate
CreateCharacterRequest = CharacterCreate
HunterAttributesEdgeModel = CharacterHunterEdge
UpdateCharacterInventoryItemRequest = InventoryItemUpdate
UpdateCharacterRequest = CharacterUpdate
from .companies import (
    Company,
    CompanyCreate,
    CompanyPermissions,
    CompanySettings,
    CompanyUpdate,
    NewCompanyResponse,
    _GrantAccess,
)

# Backwards compatibility aliases for companies
CreateCompanyRequest = CompanyCreate
GrantAccessRequest = _GrantAccess
UpdateCompanyRequest = CompanyUpdate
from .developers import (
    MeDeveloper,
    MeDeveloperCompanyPermission,
    MeDeveloperUpdate,
    MeDeveloperWithApiKey,
)

# Backwards compatibility alias for developers
UpdateMeDeveloperRequest = MeDeveloperUpdate
from .diceroll import DicerollCreate, Dicreoll, _DicerollQuickrollCreate

# Backwards compatibility aliases for diceroll
CreateDicreollQuickrollRequest = _DicerollQuickrollCreate
CreateDicreollRequest = DicerollCreate
from .dictionary import (
    DictionaryTerm,
    DictionaryTermCreate,
    DictionaryTermUpdate,
)

# Backwards compatibility aliases for dictionary
CreateDictionaryTermRequest = DictionaryTermCreate
UpdateDictionaryTermRequest = DictionaryTermUpdate
from .global_admin import (
    Developer,
    DeveloperCompanyPermission,
    DeveloperCreate,
    DeveloperUpdate,
    DeveloperWithApiKey,
)

# Backwards compatibility aliases for global_admin
CreateDeveloperRequest = DeveloperCreate
UpdateDeveloperRequest = DeveloperUpdate
from .pagination import PaginatedResponse
from .shared import (
    CharacterSpecialty,
    NameDescriptionSubDocument,
    Note,
    NoteCreate,
    NoteUpdate,
    RollStatistics,
    S3Asset,
    Trait,
    WerewolfGift,
    WerewolfRite,
)

# Backwards compatibility aliases for notes
CreateNoteRequest = NoteCreate
UpdateNoteRequest = NoteUpdate
from .system import SystemHealth
from .users import (
    CampaignExperience,
    DiscordProfile,
    Quickroll,
    QuickrollCreate,
    QuickrollUpdate,
    User,
    UserCreate,
    UserUpdate,
    _ExperienceAddRemove,
)

# Backwards compatibility aliases for users
CreateQuickrollRequest = QuickrollCreate
CreateUserRequest = UserCreate
ExperienceAddRemoveRequest = _ExperienceAddRemove
UpdateQuickrollRequest = QuickrollUpdate
UpdateUserRequest = UserUpdate

__all__ = [
    "AssignCharacterTraitRequest",
    "BookCreate",
    "BookUpdate",
    "Campaign",
    "CampaignBook",
    "CampaignChapter",
    "CampaignCreate",
    "CampaignExperience",
    "CampaignUpdate",
    "ChapterCreate",
    "ChapterUpdate",
    "Character",
    "CharacterConcept",
    "CharacterCreate",
    "CharacterEdgeAndPerksDTO",  # Backwards compat alias for EdgeAndPerks
    "CharacterInventoryItem",  # Backwards compat alias for InventoryItem
    "CharacterPerkDTO",  # Backwards compat alias for Perk
    "CharacterSpecialty",
    "CharacterTrait",
    "CharacterTraitModifyRequest",
    "CharacterTraitValueOptionsResponse",
    "CharacterUpdate",
    "ChargenSessionFinalizeDTO",
    "ChargenSessionResponse",
    "Company",
    "CompanyCreate",
    "CompanyPermissions",
    "CompanySettings",
    "CompanyUpdate",
    "CreateAutogenerateDTO",
    "CreateBookRequest",
    "CreateCampaignRequest",
    "CreateChapterRequest",
    "CreateCharacterInventoryItemRequest",  # Backwards compat alias for InventoryItemCreate
    "CreateCharacterRequest",  # Backwards compat alias for CharacterCreate
    "CreateCharacterTraitRequest",
    "CreateCompanyRequest",
    "CreateDeveloperRequest",
    "CreateDicreollQuickrollRequest",
    "CreateDicreollRequest",
    "CreateDictionaryTermRequest",
    "CreateNoteRequest",
    "CreateQuickrollRequest",
    "CreateUserRequest",
    "Developer",
    "DeveloperCompanyPermission",
    "DeveloperCreate",
    "DeveloperUpdate",
    "DeveloperWithApiKey",
    "DicerollCreate",
    "Dicreoll",
    "DictionaryTerm",
    "DictionaryTermCreate",
    "DictionaryTermUpdate",
    "DiscordProfile",
    "EdgeAndPerks",
    "ExperienceAddRemoveRequest",
    "GrantAccessRequest",
    "HunterAttributes",
    "HunterAttributesCreate",
    "HunterAttributesEdgeModel",  # Backwards compat alias for HunterEdge
    "HunterAttributesUpdate",
    "HunterEdge",
    "HunterEdgePerk",
    "InventoryItem",
    "InventoryItemCreate",
    "InventoryItemUpdate",
    "MageAttributes",
    "MeDeveloper",
    "MeDeveloperCompanyPermission",
    "MeDeveloperUpdate",
    "MeDeveloperWithApiKey",
    "NameDescriptionSubDocument",
    "NewCompanyResponse",
    "Note",
    "NoteCreate",
    "NoteUpdate",
    "PaginatedResponse",
    "Perk",
    "Quickroll",
    "QuickrollCreate",
    "QuickrollUpdate",
    "RenumberBookRequest",
    "RenumberChapterRequest",
    "RollStatistics",
    "S3Asset",
    "SheetSection",
    "SystemHealth",
    "Trait",
    "TraitCategory",
    "TraitCreate",
    "UpdateBookRequest",
    "UpdateCampaignRequest",
    "UpdateChapterRequest",
    "UpdateCharacterInventoryItemRequest",  # Backwards compat alias for InventoryItemUpdate
    "UpdateCharacterRequest",  # Backwards compat alias for CharacterUpdate
    "UpdateCompanyRequest",
    "UpdateDeveloperRequest",
    "UpdateDictionaryTermRequest",
    "UpdateMeDeveloperRequest",
    "UpdateNoteRequest",
    "UpdateQuickrollRequest",
    "UpdateUserRequest",
    "User",
    "UserCreate",
    "UserUpdate",
    "VampireAttributes",
    "VampireAttributesCreate",
    "VampireAttributesUpdate",
    "VampireClan",
    "WerewolfAttributes",
    "WerewolfAttributesCreate",
    "WerewolfAttributesUpdate",
    "WerewolfAuspice",
    "WerewolfGift",
    "WerewolfRite",
    "WerewolfTribe",
]
