"""Character Autogeneration models."""

from datetime import datetime

from pydantic import BaseModel

from vclient.constants import AbilityFocus, AutoGenExperienceLevel, CharacterClass, CharacterType

from .characters import Character


class ChargenSessionResponse(BaseModel):
    """Response containing generated character options."""

    session_id: str
    expires_at: datetime
    requires_selection: bool
    characters: list[Character]


class ChargenSessionFinalizeDTO(BaseModel):
    """Input DTO for finalizing character selection."""

    session_id: str
    selected_character_id: str


class CreateAutogenerateDTO(BaseModel):
    """Create autogenerate DTO."""

    character_type: CharacterType
    character_class: CharacterClass | None = None
    experience_level: AutoGenExperienceLevel | None = None
    skill_focus: AbilityFocus | None = None
    concept_id: str | None = None
    vampire_clan_id: str | None = None
    werewolf_tribe_id: str | None = None
    werewolf_auspice_id: str | None = None
