# AUTO-GENERATED — do not edit. Run 'uv run duty generate_sync' to regenerate.
"""Character Autogeneration service."""
from typing import TYPE_CHECKING

from vclient._sync.services.base import SyncBaseService
from vclient.constants import AbilityFocus, AutoGenExperienceLevel, CharacterClass, CharacterType
from vclient.endpoints import Endpoints
from vclient.models import (
    Character,
    ChargenSessionFinalizeDTO,
    ChargenSessionResponse,
    CreateAutogenerateDTO,
)

if TYPE_CHECKING:
    from vclient._sync.client import SyncVClient

class SyncCharacterAutogenService(SyncBaseService):
    """Service for interacting with the Character Autogeneration API."""

    def __init__(self, client: "SyncVClient", company_id: str, user_id: str, campaign_id: str) -> None:
        """Initialize the service.

        Args:
            client: The SyncVClient instance to use for requests.
            company_id: The ID of the company to operate within.
            user_id: The ID of the user to operate as.
            campaign_id: The ID of the campaign to operate within.
        """
        super().__init__(client)
        self._company_id = company_id
        self._user_id = user_id
        self._campaign_id = campaign_id

    def _format_endpoint(self, endpoint: str, **kwargs: str) -> str:
        """Format an endpoint with the scoped company_id, user_id, and campaign_id plus any extra params."""
        return endpoint.format(company_id=self._company_id, user_id=self._user_id, campaign_id=self._campaign_id, **kwargs)

    def generate_character(self, *, character_type: CharacterType, character_class: CharacterClass | None=None, experience_level: AutoGenExperienceLevel | None=None, skill_focus: AbilityFocus | None=None, concept_id: str | None=None, vampire_clan_id: str | None=None, werewolf_tribe_id: str | None=None, werewolf_auspice_id: str | None=None) -> Character:
        """Generate a character.

        Args:
            character_type: The type of character to generate.
            character_class: The class of character to generate.
            experience_level: The experience level of character to generate.
            skill_focus: The skill focus of character to generate.
            concept_id: The concept ID of character to generate.
            vampire_clan_id: The vampire clan ID of character to generate.
            werewolf_tribe_id: The werewolf tribe ID of character to generate.
            werewolf_auspice_id: The werewolf auspice ID of character to generate.

        Returns:
            The generated character.

        Raises:
            RequestValidationError: If the input parameters fail client-side validation.
            ValidationError: If the request data is invalid.
            AuthorizationError: If you don't have appropriate access.
        """
        body = self._validate_request(CreateAutogenerateDTO, character_type=character_type, character_class=character_class, experience_level=experience_level, skill_focus=skill_focus, concept_id=concept_id, vampire_clan_id=vampire_clan_id, werewolf_tribe_id=werewolf_tribe_id, werewolf_auspice_id=werewolf_auspice_id)
        response = self._post(self._format_endpoint(Endpoints.AUTOGENERATE), json=body.model_dump(exclude_none=True, exclude_unset=True, mode="json"))
        return Character.model_validate(response.json())

    def start_chargen_session(self) -> ChargenSessionResponse:
        """Start a chargen session."""
        response = self._post(self._format_endpoint(Endpoints.CHARGEN_START))
        return ChargenSessionResponse.model_validate(response.json())

    def finalize_chargen_session(self, session_id: str, selected_character_id: str) -> Character:
        """Finalize a chargen session."""
        body = self._validate_request(ChargenSessionFinalizeDTO, session_id=session_id, selected_character_id=selected_character_id)
        response = self._post(self._format_endpoint(Endpoints.CHARGEN_FINALIZE), json=body.model_dump(exclude_none=True, exclude_unset=True, mode="json"))
        return Character.model_validate(response.json())
