"""Testing utilities for downstream applications using vclient.

Requires the 'testing' extra: pip install vclient[testing]
"""

try:
    import polyfactory  # noqa: F401
except ImportError as e:
    msg = (
        "vclient.testing requires the 'testing' extra. "
        "Install it with: pip install vclient[testing]"
    )
    raise ImportError(msg) from e

from vclient._sync.testing import SyncFakeVClient
from vclient.testing._client import FakeVClient
from vclient.testing._factories import (
    AdminUserFactory,
    AppleProfileFactory,
    AssetFactory,
    AuditLogDetailFactory,
    AuditLogFactory,
    BulkAssignTraitFailureFactory,
    BulkAssignTraitResponseFactory,
    BulkAssignTraitSuccessFactory,
    CampaignBookDetailFactory,
    CampaignBookFactory,
    CampaignChapterDetailFactory,
    CampaignChapterFactory,
    CampaignExperienceFactory,
    CampaignFactory,
    CharacterConceptFactory,
    CharacterDetailFactory,
    CharacterFactory,
    CharacterFullSheetFactory,
    CharacterTraitFactory,
    CharacterTraitValueOptionsResponseFactory,
    ChargenSessionResponseFactory,
    CompanyFactory,
    CompanyPermissionsFactory,
    DeveloperFactory,
    DeveloperWithApiKeyFactory,
    DicerollFactory,
    DictionaryTermFactory,
    FullSheetTraitCategoryFactory,
    FullSheetTraitSectionFactory,
    FullSheetTraitSubcategoryFactory,
    GitHubProfileFactory,
    GoogleProfileFactory,
    InventoryItemFactory,
    MeDeveloperFactory,
    MeDeveloperWithApiKeyFactory,
    NewCompanyResponseFactory,
    NoteFactory,
    QuickrollFactory,
    RollStatisticsFactory,
    ServerLogEntryFactory,
    SheetSectionFactory,
    SystemHealthFactory,
    TraitCategoryFactory,
    TraitFactory,
    TraitSubcategoryFactory,
    UserDetailFactory,
    UserFactory,
    UserLookupResultFactory,
    VampireClanFactory,
    WerewolfAuspiceFactory,
    WerewolfTribeFactory,
)
from vclient.testing._routes import Routes, RouteSpec

__all__ = [
    "AdminUserFactory",
    "AppleProfileFactory",
    "AssetFactory",
    "AuditLogDetailFactory",
    "AuditLogFactory",
    "BulkAssignTraitFailureFactory",
    "BulkAssignTraitResponseFactory",
    "BulkAssignTraitSuccessFactory",
    "CampaignBookDetailFactory",
    "CampaignBookFactory",
    "CampaignChapterDetailFactory",
    "CampaignChapterFactory",
    "CampaignExperienceFactory",
    "CampaignFactory",
    "CharacterConceptFactory",
    "CharacterDetailFactory",
    "CharacterFactory",
    "CharacterFullSheetFactory",
    "CharacterTraitFactory",
    "CharacterTraitValueOptionsResponseFactory",
    "ChargenSessionResponseFactory",
    "CompanyFactory",
    "CompanyPermissionsFactory",
    "DeveloperFactory",
    "DeveloperWithApiKeyFactory",
    "DicerollFactory",
    "DictionaryTermFactory",
    "FakeVClient",
    "FullSheetTraitCategoryFactory",
    "FullSheetTraitSectionFactory",
    "FullSheetTraitSubcategoryFactory",
    "GitHubProfileFactory",
    "GoogleProfileFactory",
    "InventoryItemFactory",
    "MeDeveloperFactory",
    "MeDeveloperWithApiKeyFactory",
    "NewCompanyResponseFactory",
    "NoteFactory",
    "QuickrollFactory",
    "RollStatisticsFactory",
    "RouteSpec",
    "Routes",
    "ServerLogEntryFactory",
    "SheetSectionFactory",
    "SyncFakeVClient",
    "SystemHealthFactory",
    "TraitCategoryFactory",
    "TraitFactory",
    "TraitSubcategoryFactory",
    "UserDetailFactory",
    "UserFactory",
    "UserLookupResultFactory",
    "VampireClanFactory",
    "WerewolfAuspiceFactory",
    "WerewolfTribeFactory",
]
